version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: yamdb_final:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  web-prepare:
    image: yamdb_final:latest
    volumes:
      - static_value:/app/static/:rw
    env_file:
      - ./.env
    command:
      - pre-run

  web-migrate:
    image: yamdb_final:latest
#    restart: on-failure
    depends_on:
      - db
    env_file:
      - ./.env
    command:
      - migrate

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ../infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/var/html/static/:ro
    depends_on:
      - web

volumes:
  static_value:
